
### Web 页面无法响应对 DAG 文件的改动

#### 问题描述

对 dags 中的 .dag 文件修改后，Airflow 的 scheduler 会定时读取 .dag 文件并更新 DAG 对象。DAG 对象的变化又会反映到 Web 页面上，具体就是 Graph View 和 Code 页面上。

本次出现的问题是对 .dag 文件的修改并没有表现在 Graph View 和 Code 页面上。

#### 查看原因

应该是调度(scheduler)进程的问题。去查看关于问题 dag 的调度日志(logs/scheduler/latest/dataplatform_update_data6.py.log)，一直不断打印如下日志:
```sh
[2022-07-18 13:15:20,370] {processor.py:162} INFO - Started process (PID=59272) to work on /home/airflow/airflow/dags/dataplatform_update_data6.py
[2022-07-18 13:15:20,371] {processor.py:613} INFO - Processing file /home/airflow/airflow/dags/dataplatform_update_data6.py for tasks to queue
[2022-07-18 13:15:20,372] {logging_mixin.py:109} INFO - [2022-07-18 13:15:20,372] {dagbag.py:496} INFO - Filling up the DagBag from /home/airflow/airflow/dags/dataplatform_update_data6.py
[2022-07-18 13:15:20,436] {logging_mixin.py:109} INFO - [2022-07-18 13:15:20,425] {dagbag.py:524} ERROR - cannot import name 'pass_context' from 'jinja2.utils' (/home/airflow/anaconda3/lib/python3.8/site-packages/jinja2/utils.py)
Traceback (most recent call last):
  File "/home/airflow/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 511, in collect_dags
    found_dags = self.process_file(filepath, only_if_updated=only_if_updated, safe_mode=safe_mode)
  File "/home/airflow/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 298, in process_file
    found_dags = self._process_modules(filepath, mods, file_last_changed_on_disk)
  File "/home/airflow/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 398, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 422, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 432, in _bag_dag
    dag.resolve_template_files()
  File "/home/airflow/anaconda3/lib/python3.8/site-packages/airflow/models/dag.py", line 986, in resolve_template_files
    t.resolve_template_files()
  File "/home/airflow/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1118, in resolve_template_files
    env = self.dag.get_template_env()
  File "/home/airflow/anaconda3/lib/python3.8/site-packages/airflow/models/dag.py", line 1007, in get_template_env
    env = airflow.templates.SandboxedEnvironment(**jinja_env_options)  # type: ignore
  File "/home/airflow/anaconda3/lib/python3.8/site-packages/jinja2/sandbox.py", line 339, in __init__
    """Return an undefined object for unsafe attributes."""
  File "/home/airflow/anaconda3/lib/python3.8/site-packages/jinja2/environment.py", line 359, in __init__
    self.policies = DEFAULT_POLICIES.copy()
  File "/home/airflow/anaconda3/lib/python3.8/site-packages/jinja2/environment.py", line 108, in load_extensions
    environment: "Environment",
  File "/home/airflow/anaconda3/lib/python3.8/site-packages/jinja2/utils.py", line 131, in import_string
    " old name will be removed in Jinja 3.1.",
  File "/home/airflow/anaconda3/lib/python3.8/site-packages/jinja2/ext.py", line 18, in <module>
    from .utils import pass_context
ImportError: cannot import name 'pass_context' from 'jinja2.utils' (/home/airflow/anaconda3/lib/python3.8/site-packages/jinja2/utils.py)
```

根据唯一的一条 ERROR 日志:
```sh
ERROR - cannot import name 'pass_context' from 'jinja2.utils' (/home/airflow/anaconda3/lib/python3.8/site-packages/jinja2/utils.py)
```
猜测应该是 jinja2 的问题。

jinja2 是 Airflow 使用的一种 python 模板引擎，安装 Airflow 会自动安装这个依赖，在这之前运行还是正常的。

查看 jinja2 依赖的安装目录，在 3 月 16 日时有过一次更新。在存放 dag 文件的目录下又查看了几个在这个日期之后修改过的其他文件，发现 Web 页面对这些文件的修改是正常响应的。所以不确定是否真的是 jinja2 依赖的问题。

#### 再次查看原因

Airflow 的调度进程(scheduler)还有一个日志(logs/dag_processor_manager/dag_processor_manager.log)，这个日志记录了对所有 dag 文件的当前调用状态。如下:
```sh
DAG File Processing Stats

File Path                                                    PID    Runtime      # DAGs    # Errors  Last Runtime    Last Run
-----------------------------------------------------------  -----  ---------  --------  ----------  --------------  -------------------
/home/airflow/airflow/dags/dataplatform_update_data6.py                                 0           0  0.10s           2022-07-18T13:32:59
/home/airflow/airflow/dags/email_while_error.py                                         0           0  0.12s           2022-07-18T13:32:48
/home/airflow/airflow/dags/zyyx_factor_update.py                                        1           0  0.21s           2022-07-18T13:32:49
/home/airflow/airflow/dags/check_mkt.py                                                 1           0  0.20s           2022-07-18T13:32:48
/home/airflow/airflow/dags/queue_example.py                                             1           0  0.12s           2022-07-18T13:32:48
/home/airflow/airflow/dags/this_test.py                                                 1           0  0.15s           2022-07-18T13:32:57
================================================================================
```
`# DAGs` 表示这个文件当前活跃的 DAG 对象个数，`/home/airflow/airflow/dags/dataplatform_update_data6.py` 对应的是 0，表示没有活跃的 DAG 对象。

猜测可能确实是因为 jinja2 问题导致模板解析 dag 文件失败，没能产生 DAG 对象导致异常。

再看针对 dag 文件的 scheduler 日志下的唯一一条 ERROR 日志:
```sh
ERROR - cannot import name 'pass_context' from 'jinja2.utils' 
```
未能从 jinja2.utils 中引用到 pass_context 。

去jinja官网查看最近的[更新变化记录](https://jinja.palletsprojects.com/en/3.1.x/changes)，从 Version 2.x 到 Version 3.x 变动很大，在 Version 3.0.0 的变化记录中看到了这样的说明:
```sh
The function and filter decorators have been renamed and unified. The old names are deprecated. #1381
    pass_context replaces contextfunction and contextfilter.
    ...
```
看起来像是新的 jinja2 版本中关于 pass_context(是我英语不好吗？上面的意思明明是 pass_context 替代了 context*，但实际代码中却是后两者替代了前者...)。

尝试去 Airflow 的源码中查找哪个地方用到了 pass_context 。只在 send_email.py 文件的一处有用到:
```py
@click.group(context_settings=dict(help_option_names=["-h", "--help"]))
@click.pass_context
@click.option(
```
看起来是和邮件有关。而 Airflow 中与邮件有关的操作对象是 EmailOperator。

看了一下自 3 月 16 日修改过的 dag 文件，没有影响的都没有使用 EmailOperator 。

之后验证了一下，确实如此。

#### 问题原因

jinja2 版本太高，导致 Airflow 对含有 EmailOperator 的 .dag 文件解析过程出现问题，未能生成 DAG 对象，近而无法反映到 web 页面中。
