
Go 语言引入了三个函数来进行异常错误的处理，即 defer(), panic() recover() 。

### panic

panic() 函数常用在出现不可恢复错误的地方，如缓冲区溢出、数组越界、空指针异常等。

在 Go 语言中，执行错误(如缓冲区溢出、数组越界、空指针异常等)会触发运行时异常，即 `panic`。运行时异常用来表示非常严重的不可恢复的错误。写法如下:
```go
    func panic(interface{})
```
该函数接受任何值作为参数，一旦执行就会终止程序运行。由于运行 panic() 函数会造成程序崩溃，所以一般开发人员不愿意看到 panic 异常的情况，然而这无法避免，为此 Go 提供了一种专门恢复 panic 状态的函数 recover() 。

### defer

必须先声明 defer，才能在 defer 修饰的函数中捕获到(recover)异常。普通函数在执行的时候发生了运行时异常，则运行 defer(若有)，defer 处理完后再返回。

在多层嵌套的函数调用中调用异常，可以马上中止当前函数的执行，defer 语句保证执行并把控制权交还给接收到异常的函数调用者。这样向上冒泡直到最顶层，并执行(每层的)defer，在栈顶程序处崩溃，并在命令行中用运行时异常的值报告异常情况。

注意，defer 关键字下的语句是直到所在的函数执行完毕时执行，而不是出作用域执行。

[defer出函数才执行](t/07_defer.go)

不过一般不要随意用 panic() 中止程序，必须尽力补救异常和错误处理以便让程序能继续执行。错误和异常处理一般规则如下:
* 在包内部，应该用 recover() 对运行时异常进行捕获。
* 向包的调用者返回错误值(而不是直接发出异常)。

关于 defer 的使用，有三个规则:
规则一: defer 声明时，其后面函数参数会被实时解析
规则二: defer 执行顺序为先进后出
规则三: defer 可以读取函数的有名返回值

[规则一示例](t/07_defer_rule_one.go)

关于规则三，有 defer 的 return 过程执行顺序是这样的: 为返回值赋值、调用 defer 修饰的函数、执行 return 语句。如果是有名返回值，返回值变量可视为引用赋值，就能被 defer 代码修改。

[规则三示例](t/07_defer_rule_thr.go)

defer 通常用于资源的释放，示例如下:
```go
    func CopyFile(dst, src string) (w int64, err error) {
        srcFile, err := os.Open(src)
        if err != nil {
            return
        }
        defer srcFile.Close()

        dstFile, err := os.Create(dstName)
        if err != nil {
            return
        }
        defer dstFile.Close()

        return io.Copy(dstFile, srcFile)
    }
```
上述代码中，即使 CopyFile 函数抛出异常，仍然可以保证 dstFile 和 srcFile 会被正常关闭。

根据 defer 延迟执行的特性，可以利用它来计算代码块的执行时间。

[使用defer计算函数执行时间](t/07_defer_time_cost.go)

### recover

recover() 内建函数用于从异常或错误场景中恢复，让程序可以从异常中重新获得控制权，停止中止过程而恢复正常执行。定义如下:
```go
    func recover() interface{}
```

recover() 函数只能在 defer 修饰的函数中使用，用于取得异常传递过来的错误值。如果是正常执行，调用 recover() 会返回 nil，且没有其他效果。如果异常传递过来的值是 nil，则 recover() 函数返回的值也是 nil，所以异常时的参数值不使用 nil 。

[程序示例](t/07_recover_from_panic.go)
